/**
 * @fileoverview Constantes de códigos de error de la aplicación
 * @description Define todos los códigos de error personalizados de la aplicación
 */

module.exports = {
    // Errores de autenticación
    AUTH: {
        INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
        TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
        TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
        ACCESS_DENIED: 'AUTH_ACCESS_DENIED',
        USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
        USER_INACTIVE: 'AUTH_USER_INACTIVE'
    },

    // Errores de validación
    VALIDATION: {
        REQUIRED_FIELD: 'VALIDATION_REQUIRED_FIELD',
        INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',
        INVALID_TYPE: 'VALIDATION_INVALID_TYPE',
        OUT_OF_RANGE: 'VALIDATION_OUT_OF_RANGE',
        DUPLICATE_VALUE: 'VALIDATION_DUPLICATE_VALUE',
        INVALID_EMAIL: 'VALIDATION_INVALID_EMAIL',
        INVALID_PHONE: 'VALIDATION_INVALID_PHONE'
    },

    // Errores de formularios FSO
    FSO: {
        FORM_NOT_FOUND: 'FSO_FORM_NOT_FOUND',
        DUPLICATE_ORDER_NUMBER: 'FSO_DUPLICATE_ORDER_NUMBER',
        INVALID_STATE: 'FSO_INVALID_STATE',
        CANNOT_UPDATE: 'FSO_CANNOT_UPDATE',
        CANNOT_DELETE: 'FSO_CANNOT_DELETE',
        PROCESSING_ERROR: 'FSO_PROCESSING_ERROR'
    },

    // Errores de archivos
    FILE: {
        NOT_FOUND: 'FILE_NOT_FOUND',
        TOO_LARGE: 'FILE_TOO_LARGE',
        INVALID_TYPE: 'FILE_INVALID_TYPE',
        CORRUPTED: 'FILE_CORRUPTED',
        UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
        DOWNLOAD_FAILED: 'FILE_DOWNLOAD_FAILED',
        DELETE_FAILED: 'FILE_DELETE_FAILED'
    },

    // Errores de PDF
    PDF: {
        PROCESSING_FAILED: 'PDF_PROCESSING_FAILED',
        GENERATION_FAILED: 'PDF_GENERATION_FAILED',
        EXTRACTION_FAILED: 'PDF_EXTRACTION_FAILED',
        INVALID_FORMAT: 'PDF_INVALID_FORMAT',
        TOO_MANY_PAGES: 'PDF_TOO_MANY_PAGES'
    },

    // Errores de base de datos
    DATABASE: {
        CONNECTION_FAILED: 'DB_CONNECTION_FAILED',
        QUERY_FAILED: 'DB_QUERY_FAILED',
        TRANSACTION_FAILED: 'DB_TRANSACTION_FAILED',
        CONSTRAINT_VIOLATION: 'DB_CONSTRAINT_VIOLATION',
        TIMEOUT: 'DB_TIMEOUT'
    },

    // Errores de sistema
    SYSTEM: {
        INTERNAL_ERROR: 'SYSTEM_INTERNAL_ERROR',
        SERVICE_UNAVAILABLE: 'SYSTEM_SERVICE_UNAVAILABLE',
        TIMEOUT: 'SYSTEM_TIMEOUT',
        MAINTENANCE_MODE: 'SYSTEM_MAINTENANCE_MODE',
        RATE_LIMIT_EXCEEDED: 'SYSTEM_RATE_LIMIT_EXCEEDED'
    },

    // Errores de Puppeteer
    PUPPETEER: {
        BROWSER_FAILED: 'PUPPETEER_BROWSER_FAILED',
        PAGE_LOAD_FAILED: 'PUPPETEER_PAGE_LOAD_FAILED',
        FORM_SUBMIT_FAILED: 'PUPPETEER_FORM_SUBMIT_FAILED',
        SESSION_EXPIRED: 'PUPPETEER_SESSION_EXPIRED'
    },

    // Errores de email
    EMAIL: {
        SEND_FAILED: 'EMAIL_SEND_FAILED',
        INVALID_TEMPLATE: 'EMAIL_INVALID_TEMPLATE',
        CONFIGURATION_ERROR: 'EMAIL_CONFIGURATION_ERROR'
    }
};
